version: '3.8'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    container_name: rocketchat
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0
      - DEPLOY_METHOD=docker
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    labels:
      - "traefik.enable=false"

  # MongoDB replica set initialization
  mongo-init-replica:
    image: mongo:5.0
    container_name: mongo-init-replica
    command: >
      bash -c "
        sleep 5;
        mongosh --host mongo:27017 --eval \"
          rs.initiate({
            _id: 'rs0',
            members: [ { _id: 0, host: 'mongo:27017' } ]
          })
        \"
      "
    depends_on:
      - mongo
    restart: "no"

volumes:
  data:
  uploads:

